### Login
POST http://localhost:5134/api/auth/login
Content-Type: application/json

{
    "username": "user",
    "password": "pass"
}

### GET all tasks (initially empty)
GET http://localhost:5134/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsIm5iZiI6MTc0MjI3MzY1OCwiZXhwIjoxNzQyMjc3MjU4LCJpc3MiOiJ5b3VyLWlzc3VlciIsImF1ZCI6InlvdXItYXVkaWVuY2UifQ.itd2lkJA1xEHZi8xQS0he_x-CagVufWvW8Vc76KkrDc

### POST a new task
POST http://localhost:5134/api/tasks
Content-Type: application/json

{
    "title": "Home Work",
    "isCompleted": false
}

### GET all tasks (should show the posted task)
GET http://localhost:5134/api/tasks
Content-Type: application/json

### GET task by ID (ID 1)
GET http://localhost:5134/api/tasks/2
Content-Type: application/json

### PUT update task (ID 1)
PUT http://localhost:5134/api/tasks/2
Content-Type: application/json

{
    "id": 2,
    "title": "Updated Task",
    "isCompleted": true
}

### GET task by ID (verify update)
GET http://localhost:5134/api/tasks/1
Content-Type: application/json

### DELETE task (ID 1)
DELETE http://localhost:5134/api/tasks/4
Content-Type: application/json

### GET all tasks (should be empty again)
GET http://localhost:5134/api/tasks
Content-Type: application/json